export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_FALLIDO = 'REGISTRO_FALLIDO'
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA'

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_FALLIDO = 'LOGIN_FALLIDO'

export const CERRAR_SESION = 'CERRAR_SESION'

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'