import React from 'react'
import Head from 'next/head'

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>NodeSend</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />
            </Head>
            {
                // eslint-disable-next-line @next/next/no-img-element
                <img src="logo.svg" alt="nodesend" />
            }
            <div className="bg-gray-100 min-h-screen">
                <div className="container mx-auto">
                    <div className="pt-20">
                        { children }
                    </div>
                </div>
            </div>
        </>
    )
}

export default Layout
