import React from 'react'
import Head from 'next/head'
import Header from './Header';

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>NodeSend</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />
            </Head>
            <div className="min-h-screen bg-gray-100">
                <div className="container mx-auto">
                    <Header />
                    <div className="mt-20">
                        { children }
                    </div>
                </div>
            </div>
        </>
    )
}

export default Layout
